spring.application.name=sanos-salvos-notificaciones
server.port=8086

# PostgreSQL: Flexible para IntelliJ (localhost) o Docker (DB_HOST)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/notificaciones_db
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka: Flexible para local o contenedor
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
spring.kafka.consumer.group-id=notificaciones-group

# JWT
jwt.secret=sanosysalvos1234
jwt.expiration=86400000